name: pint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: bcmath, exif, intl
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Check code style
        run: vendor/bin/pint --test
